In [14]:
from numpy import random as rd
import statistics as stats
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [15]:
def bernoulli_squirrels(p, P0, N):
    P = np.zeros(N+1)
    N_vec = np.arange(N+1)
    
    for i in N_vec:
        if (i==0):
            P[i] = P0
        else:
            P[i] = rd.binomial(P[i-1], p, 1)

            
    return P

In [16]:
N = 1
P0 = 100
p = 0.32
sets = 100

results = np.zeros((N+1, sets))

times = np.arange(sets) 

for i in times:
    rd.seed(i)
    results[:, i] = bernoulli_squirrels(p, P0, N)

df_bernoulli = pd.DataFrame(results)

df_bernoulli

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1,33.0,30.0,26.0,34.0,35.0,30.0,39.0,28.0,36.0,28.0,...,34.0,33.0,26.0,31.0,27.0,35.0,29.0,24.0,32.0,15.0

In [17]:
mean = np.zeros(2)

for i in range(len(mean)):
        mean[i] = stats.mean(df_bernoulli.iloc[i])
        
sd = np.zeros(2)

for i in range(len(sd)):
        sd[i] = stats.stdev(df_bernoulli.iloc[i])
        
summary_bernoulli = pd.DataFrame({
    'Mean': mean,
    'Standard Deviation': sd
})

summary_bernoulli

     Mean  Standard Deviation
0  100.00            0.000000
1   31.66            5.051692

In [18]:
N = 15
P0 = 31.66
p = 0.68
sets = 100

results = np.zeros((N+1, sets))

times = np.arange(sets) 

for i in times:
    rd.seed(i)
    results[:, i] = bernoulli_squirrels(p, P0, N)

df_bernoulli = pd.DataFrame(results)

df_bernoulli

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,31.66,31.66,31.66,31.66,31.66,31.66,31.66,31.66,31.66,31.66,...,31.66,31.66,31.66,31.66,31.66,31.66,31.66,31.66,31.66,31.66
1,21.00,22.00,22.00,21.00,16.00,23.00,18.00,25.00,18.00,27.00,...,24.00,23.00,18.00,20.00,20.00,23.00,23.00,19.00,20.00,20.00
2,13.00,14.00,19.00,13.00,11.00,13.00,13.00,15.00,8.00,18.00,...,19.00,17.00,11.00,13.00,13.00,18.00,13.00,9.00,13.00,14.00
3,8.00,14.00,13.00,10.00,4.00,10.00,7.00,11.00,4.00,12.00,...,8.00,13.00,8.00,10.00,8.00,10.00,7.00,6.00,10.00,8.00
4,5.00,10.00,9.00,7.00,2.00,5.00,7.00,7.00,3.00,10.00,...,4.00,11.00,6.00,4.00,6.00,6.00,3.00,5.00,6.00,8.00
5,4.00,8.00,6.00,3.00,1.00,3.00,6.00,2.00,3.00,8.00,...,4.00,8.00,6.00,3.00,4.00,4.00,2.00,3.00,4.00,4.00
6,2.00,7.00,5.00,1.00,1.00,2.00,4.00,1.00,3.00,6.00,...,3.00,5.00,3.00,2.00,3.00,2.00,2.00,3.00,4.00,3.00
7,2.00,6.00,4.00,1.00,0.00,1.00,3.00,1.00,2.00,4.00,...,2.00,3.00,2.00,0.00,2.00,1.00,2.00,0.00,3.00,3.00
8,1.00,5.00,2.00,1.00,0.00,1.00,2.00,1.00,2.00,3.00,...,1.00,2.00,1.00,0.00,2.00,1.00,1.00,0.00,2.00,3.00
9,0.00,4.00,2.00,1.00,0.00,1.00,2.00,1.00,1.00,3.00,...,1.00,0.00,1.00,0.00,0.00,0.00,1.00,0.00,2.00,0.00
10,0.00,3.00,2.00,1.00,0.00,1.00,1.00,1.00,1.00,2.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,2.00,0.00
11,0.00,2.00,1.00,1.00,0.00,1.00,1.00,1.00,1.00,2.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,2.00,0.00
12,0.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,1.00,1.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,2.00,0.00
13,0.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00
14,0.00,0.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00
15,0.00,0.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00

In [19]:
mean = np.zeros(16)

for i in range(len(mean)):
        mean[i] = stats.mean(df_bernoulli.iloc[i])
        
sd = np.zeros(16)

for i in range(len(sd)):
        sd[i] = stats.stdev(df_bernoulli.iloc[i])
        
summary_bernoulli = pd.DataFrame({
    'Mean': mean,
    'Standard Deviation': sd
})

summary_bernoulli

     Mean  Standard Deviation
0   31.66            0.000000
1   21.28            2.550817
2   14.44            2.606596
3    9.55            2.633794
4    6.65            2.306666
5    4.54            2.061773
6    3.04            1.675251
7    2.14            1.435622
8    1.47            1.114233
9    0.98            1.024744
10   0.67            0.817177
11   0.49            0.643460
12   0.33            0.513554
13   0.21            0.409360
14   0.13            0.337998
15   0.13            0.337998

In [20]:
N = 1
P0 = 100
p = 0.34
sets = 100

results = np.zeros((N+1, sets))

times = np.arange(sets) 

for i in times:
    rd.seed(i)
    results[:, i] = bernoulli_squirrels(p, P0, N)

df_bernoulli = pd.DataFrame(results)

df_bernoulli

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1,40.0,32.0,28.0,36.0,37.0,32.0,41.0,30.0,25.0,30.0,...,36.0,35.0,28.0,33.0,29.0,37.0,31.0,26.0,34.0,39.0

In [21]:
mean = np.zeros(2)

for i in range(len(mean)):
        mean[i] = stats.mean(df_bernoulli.iloc[i])
        
sd = np.zeros(2)

for i in range(len(sd)):
        sd[i] = stats.stdev(df_bernoulli.iloc[i])
        
summary_bernoulli = pd.DataFrame({
    'Mean': mean,
    'Standard Deviation': sd
})

summary_bernoulli

     Mean  Standard Deviation
0  100.00            0.000000
1   33.41            5.152414

In [22]:
N = 15
P0 = 33.41
p = 0.71
sets = 100

results = np.zeros((N+1, sets))

times = np.arange(sets) 

for i in times:
    rd.seed(i)
    results[:, i] = bernoulli_squirrels(p, P0, N)

df_bernoulli = pd.DataFrame(results)

df_bernoulli

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,33.41,33.41,33.41,33.41,33.41,33.41,33.41,33.41,33.41,33.41,...,33.41,33.41,33.41,33.41,33.41,33.41,33.41,33.41,33.41,33.41
1,23.00,24.00,24.00,23.00,19.00,25.00,20.00,27.00,20.00,29.00,...,26.00,26.00,20.00,23.00,22.00,25.00,26.00,21.00,22.00,22.00
2,15.00,16.00,21.00,15.00,13.00,15.00,15.00,17.00,10.00,21.00,...,21.00,20.00,13.00,16.00,15.00,20.00,15.00,11.00,15.00,16.00
3,10.00,16.00,15.00,12.00,6.00,12.00,9.00,12.00,5.00,15.00,...,10.00,15.00,10.00,12.00,10.00,12.00,9.00,8.00,12.00,10.00
4,7.00,12.00,11.00,9.00,4.00,6.00,9.00,8.00,4.00,13.00,...,5.00,13.00,7.00,6.00,7.00,8.00,5.00,6.00,7.00,10.00
5,5.00,10.00,8.00,5.00,2.00,4.00,8.00,3.00,4.00,11.00,...,4.00,10.00,7.00,4.00,5.00,6.00,3.00,3.00,5.00,6.00
6,3.00,9.00,6.00,2.00,2.00,3.00,5.00,2.00,4.00,9.00,...,3.00,6.00,4.00,3.00,4.00,3.00,3.00,3.00,5.00,4.00
7,2.00,8.00,5.00,2.00,0.00,2.00,4.00,2.00,3.00,7.00,...,3.00,4.00,3.00,0.00,3.00,2.00,3.00,0.00,4.00,3.00
8,1.00,6.00,3.00,2.00,0.00,1.00,3.00,2.00,2.00,6.00,...,2.00,3.00,2.00,0.00,3.00,2.00,2.00,0.00,3.00,3.00
9,0.00,5.00,3.00,2.00,0.00,1.00,3.00,2.00,1.00,6.00,...,2.00,1.00,2.00,0.00,1.00,1.00,1.00,0.00,3.00,0.00
10,0.00,4.00,3.00,2.00,0.00,1.00,2.00,2.00,1.00,5.00,...,1.00,1.00,0.00,0.00,1.00,0.00,1.00,0.00,3.00,0.00
11,0.00,3.00,2.00,2.00,0.00,1.00,2.00,1.00,1.00,5.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,2.00,0.00
12,0.00,2.00,1.00,2.00,0.00,0.00,1.00,0.00,1.00,2.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,2.00,0.00
13,0.00,2.00,1.00,1.00,0.00,0.00,1.00,0.00,0.00,0.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00
14,0.00,1.00,1.00,1.00,0.00,0.00,1.00,0.00,0.00,0.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00
15,0.00,1.00,1.00,1.00,0.00,0.00,1.00,0.00,0.00,0.00,...,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00

In [23]:
mean = np.zeros(16)

for i in range(len(mean)):
        mean[i] = stats.mean(df_bernoulli.iloc[i])
        
sd = np.zeros(16)

for i in range(len(sd)):
        sd[i] = stats.stdev(df_bernoulli.iloc[i])
        
summary_bernoulli = pd.DataFrame({
    'Mean': mean,
    'Standard Deviation': sd
})

summary_bernoulli

     Mean  Standard Deviation
0   33.41            0.000000
1   23.67            2.566509
2   16.79            2.682886
3   11.68            2.792052
4    8.48            2.591673
5    6.09            2.361711
6    4.28            1.928416
7    3.10            1.749459
8    2.19            1.390407
9    1.58            1.349747
10   1.16            1.152249
11   0.83            0.964575
12   0.55            0.715979
13   0.37            0.597216
14   0.25            0.479372
15   0.22            0.462317